/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: UROD Engine (https://sketchfab.com/Starven38)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/personal-computer-aa398650fe6e4baa8771c71266d842f4
Title: Personal Computer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Computer = (props) => {
  const { nodes, materials } = useGLTF("/computer.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_PC_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_LightMat_0.geometry}
              material={materials.LightMat}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Screen_0.geometry}
              material={materials.Screen}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Keyboard_0.geometry}
              material={materials.Keyboard}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/computer.gltf");

export default Computer;
